nodes:
  hosts:
    m-node-1:
      ansible_host: 172.10.10.201
      ansible_user: iamslave
      ans_host_add: 172.10.10.201  # Add this line
    m-node-2:
      ansible_host: 172.10.10.202
      ansible_user: iamnode3
      ans_host_add: 172.10.10.202  # Add this line
    m-node-3:
      ansible_host: 172.10.10.203
      ansible_user: iam-m-node-3
      ans_host_add: 172.10.10.203  # Add this line

